// Autogenerated from Pigeon (v26.1.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsLinkOsMultiplatformSdk(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsLinkOsMultiplatformSdk(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsLinkOsMultiplatformSdk(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashLinkOsMultiplatformSdk(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashLinkOsMultiplatformSdk(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashLinkOsMultiplatformSdk(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct BluetoothLePrinterData: Hashable {
  var name: String
  var address: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BluetoothLePrinterData? {
    let name = pigeonVar_list[0] as! String
    let address = pigeonVar_list[1] as! String

    return BluetoothLePrinterData(
      name: name,
      address: address
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      address,
    ]
  }
  static func == (lhs: BluetoothLePrinterData, rhs: BluetoothLePrinterData) -> Bool {
    return deepEqualsLinkOsMultiplatformSdk(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashLinkOsMultiplatformSdk(value: toList(), hasher: &hasher)
  }
}

private class LinkOsMultiplatformSdkPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return BluetoothLePrinterData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class LinkOsMultiplatformSdkPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BluetoothLePrinterData {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class LinkOsMultiplatformSdkPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return LinkOsMultiplatformSdkPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return LinkOsMultiplatformSdkPigeonCodecWriter(data: data)
  }
}

class LinkOsMultiplatformSdkPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = LinkOsMultiplatformSdkPigeonCodec(readerWriter: LinkOsMultiplatformSdkPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol LinkOsMultiplatformSdkHostApi {
  func requestBluetoothLePermissions(completion: @escaping (Result<Bool, Error>) -> Void)
  func startBluetoothLeScanning(completion: @escaping (Result<Void, Error>) -> Void)
  func printOverBluetoothLeWithoutParing(address: String, zpl: String, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class LinkOsMultiplatformSdkHostApiSetup {
  static var codec: FlutterStandardMessageCodec { LinkOsMultiplatformSdkPigeonCodec.shared }
  /// Sets up an instance of `LinkOsMultiplatformSdkHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: LinkOsMultiplatformSdkHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let requestBluetoothLePermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.wisecrab.link_os_multiplatform_sdk.LinkOsMultiplatformSdkHostApi.requestBluetoothLePermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestBluetoothLePermissionsChannel.setMessageHandler { _, reply in
        api.requestBluetoothLePermissions { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestBluetoothLePermissionsChannel.setMessageHandler(nil)
    }
    let startBluetoothLeScanningChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.wisecrab.link_os_multiplatform_sdk.LinkOsMultiplatformSdkHostApi.startBluetoothLeScanning\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startBluetoothLeScanningChannel.setMessageHandler { _, reply in
        api.startBluetoothLeScanning { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startBluetoothLeScanningChannel.setMessageHandler(nil)
    }
    let printOverBluetoothLeWithoutParingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.wisecrab.link_os_multiplatform_sdk.LinkOsMultiplatformSdkHostApi.printOverBluetoothLeWithoutParing\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      printOverBluetoothLeWithoutParingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let addressArg = args[0] as! String
        let zplArg = args[1] as! String
        api.printOverBluetoothLeWithoutParing(address: addressArg, zpl: zplArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      printOverBluetoothLeWithoutParingChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol LinkOsMultiplatformSdkFlutterApiProtocol {
  func onBluetoothLePrintersDetected(printerData printerDataArg: [BluetoothLePrinterData], completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class LinkOsMultiplatformSdkFlutterApi: LinkOsMultiplatformSdkFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: LinkOsMultiplatformSdkPigeonCodec {
    return LinkOsMultiplatformSdkPigeonCodec.shared
  }
  func onBluetoothLePrintersDetected(printerData printerDataArg: [BluetoothLePrinterData], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.com.wisecrab.link_os_multiplatform_sdk.LinkOsMultiplatformSdkFlutterApi.onBluetoothLePrintersDetected\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([printerDataArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
